version: '3'
services:
  meme-generator:
    image: shiwuliya/meme-generator:latest
    container_name: meme
    restart: always
    network_mode: "bridge"
    ports:
      - "2233:2233"
    volumes:
      - /opt/meme/data:/data/memes
    environment:
      MEME_DIRS: '["/data/memes"]'
      MEME_DISABLED_LIST: '[]'
      GIF_MAX_SIZE: '10.0'
      GIF_MAX_FRAMES: '100'
      LOG_LEVEL: 'INFO'
      PORT: '2233'
    mem_limit: 1024M # 设置1G, 防止爆内存