# name: 同步更新

# on:
#   workflow_dispatch:
#   workflow_run:
#     workflows: ["构建并推送镜像"]
#     types: [completed]
#   schedule:
#     - cron: "0 18 * * *"

# permissions:
#   contents: write

# jobs:
#   server:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 检出当前仓库代码
#         uses: actions/checkout@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: 克隆源仓库
#         run: |
#           git clone --depth=1 https://github.com/MemeCrafters/meme-generator ${{ runner.temp }}/repo 

#       - name: 同步更新文件
#         run: |
#           rsync -av ${{ runner.temp }}/repo/meme_generator/memes/ ./meme_generator/memes/

#       - name: 检查是否有更改
#         run: |
#           git status
#           if [[ -n $(git status -s) ]]; then
#             echo "HAS_CHANGES=true" >> $GITHUB_ENV
#           else
#             echo "HAS_CHANGES=false" >> $GITHUB_ENV
#           fi

#       - name: 提交并推送更改
#         if: env.HAS_CHANGES == 'true'
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git add meme_generator/memes/
#           git commit -m "同步上游仓库表情"
#           git push
